sudo: required

dist: trusty

language: node_js

node_js:
  - '8'
  - '10'
  - '12'

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

services:
  - xvfb

addons:
  - chrome: stable

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"

script: node_modules/karma/bin/karma start ./karma.conf.js --single-run
