sudo: false

language: node_js

node_js:
  - '6'
  - '8'
  - '10'

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - export CHROME_BIN=chromium-browser

services:
  - xvfb

before_script:
  - "sudo chown root /usr/lib/chromium-browser/chrome-sandbox"
  - "sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox"
