sudo: required

dist: xenial

language: node_js

node_js:
  - '8'
  - '10'
  - '12'

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

services:
  - xvfb

addons:
  - chrome: stable

before_install:
  - "export TRAVIS=1"
  - "export DISPLAY=:99.0"

scripts:
  - "npm install codecov -g"
  - "node_modules/karma/bin/karma start ./karma.conf.js --single-run"
  - "istanbul cover ./node_modules/jasmine/bin/jasmine.js"
  - codecov
